version: "3.7"

services:
  postgres:
    container_name: feastflow-api-postgres
    image: bitnami/postgresql:latest
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=feastflow
    volumes:
      - feastflow_pg_data:/bitnami/postgresql

volumes:
  feastflow_pg_data:
